name: 'Say Hello World'

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a online-script
        run: echo Hello, World!
      - name: Run a multi-line script
        run: |
          echo Add another actions to build,
          echo test, and deploy your project.